# Generated by Django 4.2 on 2023-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='money',
            new_name='value',
        ),
        migrations.AddField(
            model_name='currency',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
    ]
