# Generated by Django 4.2 on 2023-04-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_currencytransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='name',
            new_name='user',
        ),
    ]
