# Generated by Django 4.2 on 2023-04-26 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0007_alter_request_destination_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='destination_username',
            new_name='destination_user',
        ),
    ]
